import struct
from pathlib import Path

asm_patches = Path(__file__).parent.parent.parent.joinpath("files", "asm_patches")

NOP = bytes.fromhex("00F020E3")


def read_bytes_from_file(asm_patch: str) -> bytes:
    return asm_patches.joinpath(asm_patch).read_bytes()


class GenerateArmBytes:
    def __init__(self, in_game_value: int, multiply: bool) -> None:
        self.in_game_value = in_game_value
        self.multiply = multiply

    def get_value(self) -> int:
        value = self.in_game_value * 10 if self.multiply else self.in_game_value

        # Absolute cap at 1020 to prevent struct packing errors
        if value > 1020:
            value = 1020
        return value

    def rotate_value(self, value: int) -> int:
        # Rounds to the nearest multiple of 4
        value_rounded = (value // 4) * 4
        imm8 = value_rounded // 4
        return imm8

    # The original function was generated by Google Gemini, edited by Dyceron
    def add(self) -> bytes:
        """
        Generates a 4-byte ARM 'ADD R2, R2, #imm' instruction in Little Endian.
        Handles launcher (direct) and expansions (x10) up to a total of 1020.
        """
        # Get the value
        value = self.get_value()

        # 0-255: Standard rotation (0x20)
        if value <= 255:
            return struct.pack("<B", value) + b"\x20\x82\xe2"

        # 256-1020: ARM rotation 30 (0x2F)
        return struct.pack("<B", self.rotate_value(value)) + b"\x2f\x82\xe2"

    def mov(self) -> bytes:
        """
        Generates a 4-byte ARM 'MOV R8, #imm' instruction in Little Endian.
        Handles direct and x10 values up to a total of 1020.
        """
        # Get the value
        value = self.get_value()

        # 0-255: Standard rotation (0x20)
        if value <= 255:
            return struct.pack("<B", value) + b"\x80\xa0\xe3"

        # 256-1020: ARM rotation 30 (0x8F)
        return struct.pack("<B", self.rotate_value(value)) + b"\x8f\xa0\xe3"


def patch_missile_launcher(ammo_value: int) -> bytes:
    binary = read_bytes_from_file("missile_launcher.bin")
    new_instructions = GenerateArmBytes(ammo_value, False).add()
    modified_bytes = binary.replace(b"\x05\x20\x82\xe2", new_instructions)

    return modified_bytes


def patch_ammo_per_expansion(ammo_value: int) -> bytes:
    binary = read_bytes_from_file("ammo_per_expansion.bin")
    new_instructions = GenerateArmBytes(ammo_value, True).add()
    modified_bytes = binary.replace(b"\xff\x20\x82\xe2", new_instructions)

    return modified_bytes


def patch_starting_missiles(ammo_value: int) -> bytes:
    binary = read_bytes_from_file("starting_missiles.bin")
    new_instructions = GenerateArmBytes(ammo_value, True).mov()
    modified_bytes = binary.replace(b"\x32\x80\xa0\xe3", new_instructions)

    return modified_bytes
