import struct
from pathlib import Path

asm_patches = Path(__file__).parent.parent.parent.joinpath("files", "asm_patches")

NOP = bytes.fromhex("00F020E3")


def read_bytes_from_file(asm_patch: str) -> bytes:
    return asm_patches.joinpath(asm_patch).read_bytes()


class GenerateArmBytes:
    def __init__(self, in_game_value: int, multiply: bool) -> None:
        self.in_game_value = in_game_value
        self.multiply = multiply

    # The original function was generated by Google Gemini, edited by Dyceron
    def set_instruction_bytes(self, destination_register: int, operand_register: int | None) -> bytes:
        value = self.in_game_value * 10 if self.multiply else self.in_game_value

        # Absolute cap at 1020 to prevent struct packing errors
        if value > 1020:
            value = 1020

        # 0-255: Standard rotation (ie, 0x20)
        if value <= 255:
            result = struct.pack("<B", value)

        # 256-1020: ARM rotation 30 (ie, 0x2F)
        # Rounds to the nearest multiple of 4
        value_rounded = (value // 4) * 4
        imm8 = value_rounded // 4
        result = struct.pack("<B", imm8)

        # Sets the instruction bytes given registers and an operand
        dr_value = f"{destination_register}0" if value <= 255 else f"{destination_register}F"
        result += bytes.fromhex(dr_value)

        # MOV does not use an operand register
        if operand_register is not None:
            or_value = f"8{operand_register}"
            result += bytes.fromhex(or_value)

        return result

    def add(self, destination_register: int, operand_register: int | None) -> bytes:
        """
        Generates a 4-byte ARM 'ADD Rd, Rn, #imm' instruction in Little Endian.
        Handles launcher (direct) and expansions (x10) up to a total of 1020.
        """
        # Set the instruction bytes
        instruction_bytes = self.set_instruction_bytes(destination_register, operand_register)

        return instruction_bytes + b"\xe2"

    def mov(self, destination_register: int) -> bytes:
        """
        Generates a 4-byte ARM 'MOV Rd, #imm' instruction in Little Endian.
        Handles direct and x10 values up to a total of 1020.
        """
        # Set the instruction bytes
        instruction_bytes = self.set_instruction_bytes(destination_register, None)

        return instruction_bytes + b"\xa0\xe3"


def patch_missile_launcher(ammo_value: int) -> bytes:
    binary = read_bytes_from_file("missile_launcher.bin")
    new_instructions = GenerateArmBytes(ammo_value, False).add(2, 2)
    modified_bytes = binary.replace(b"\x05\x20\x82\xe2", new_instructions)

    return modified_bytes


def patch_ammo_per_expansion(ammo_value: int) -> bytes:
    binary = read_bytes_from_file("ammo_per_expansion.bin")
    new_instructions = GenerateArmBytes(ammo_value, True).add(2, 2)
    modified_bytes = binary.replace(b"\xff\x20\x82\xe2", new_instructions)

    return modified_bytes


def patch_starting_missiles(ammo_value: int) -> bytes:
    binary = read_bytes_from_file("starting_missiles.bin")
    new_instructions = GenerateArmBytes(ammo_value, True).mov(8)
    modified_bytes = binary.replace(b"\x32\x80\xa0\xe3", new_instructions)

    return modified_bytes
