import enum


class EntityType(enum.Enum):
    PLATFORM = 0
    OBJECT = 1
    PLAYER_SPAWN = 2
    DOOR = 3
    ITEM_SPAWN = 4
    ENEMY_SPAWN = 6
    TRIGGER_VOLUME = 7
    AREA_VOLUME = 8
    JUMP_PAD = 9
    POINT_MODULE = 10  # unused
    MORPH_CAMERA = 11
    OCTOLITH_FLAG = 12
    FLAG_BASE = 13
    TELEPORTER = 14
    DEFENSE_NODE = 15
    LIGHT_SOURCE = 16
    ARTIFACT = 17
    CAMERA_SEQUENCE = 18
    FORCE_FIELD = 19


class Message(enum.Enum):
    NONE = 0
    SET_ACTIVE = 5
    DESTROYED = 6
    DAMAGE = 7
    TRIGGER = 9
    UPDATE_MUSIC = 12
    GRAVITY = 15
    UNLOCK = 16
    LOCK = 17
    ACTIVATE = 18
    COMPLETE = 19
    IMPACT = 20
    DEATH = 21
    UNUSED_22 = 22
    SHIP_HATCH = 23
    UNUSED_24 = 24
    UNUSED_25 = 25
    SHOW_PROMPT = 26
    SHOW_WARNING = 27
    SHOW_OVERLAY = 28
    MOVE_ITEM_SPAWNER = 29
    SET_CAM_SEQ_AI = 30
    PLAYER_COLLIDE_WITH = 31
    BEAM_COLLIDE_WITH = 32
    UNLOCK_CONNECTORS = 33
    LOCK_CONNECTORS = 34
    PREVENT_FORM_SWITCH = 35
    UNKNOWN_36 = 36
    SET_TRIGGER_STATE = 42
    CLEAR_TRIGGER_STATE = 43
    PLATFORM_WAKEUP = 44
    PLATFORM_SLEEP = 45
    DRIP_MOAT_PLATFORM = 46
    ACTIVATE_TURRET = 48
    DECREASE_TURRET_LIGHTS = 49
    INCREASE_TURRET_LIGHTS = 50
    DEACTIVATE_TURRET = 51
    SET_BEAM_REFLECTION = 52
    SET_PLATFORM_INDEX = 53
    PLAY_SFX_SCRIPT = 54
    UNLOCK_OUBLIETTE = 56
    CHECKPOINT = 57
    ESCAPE_UPDATE1 = 58
    SET_SEEK_PLAYER_Y = 59
    LOAD_OUBLIETTE = 60
    ESCAPE_UPDATE2 = 61


class ItemType(enum.Enum):
    NONE = -1
    HEALTH_MEDIUM = 0
    HEALTH_SMALL = 1
    HEALTH_BIG = 2
    DOUBLE_DAMAGE = 3
    ENERGY_TANK = 4
    VOLT_DRIVER = 5
    MISSILE_EXPANSION = 6
    BATTLEHAMMER = 7
    IMPERIALIST = 8
    JUDICATOR = 9
    MAGMAUL = 10
    SHOCK_COIL = 11
    OMEGA_CANNON = 12
    UA_SMALL = 13
    UA_BIG = 14
    MISSILE_SMALL = 15
    MISSILE_BIG = 16
    CLOAK = 17
    UA_EXPANSION = 18
    ARTIFACT_KEY = 19
    DEATHALT = 20
    AFFINITY_WEAPON = 21
    PICK_WPN_MISSILE = 22


class PaletteId(enum.Enum):
    POWER_BEAM = 0
    VOLT_DRIVER = 1
    MISSILE = 2
    BATTLEHAMMER = 3
    IMPERIALIST = 4
    JUDICATOR = 5
    MAGMAUL = 6
    SHOCK_COIL = 7
    OMEGA_CANNON = 8
    LOCKED = 9
